pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                echo "Building" 
                sh "mvn clean install -DskipTests"
            }
        }
        stage('Test') { 
            steps {
                echo "Testing" 
                sh "./mvn test"
            }
        }
        stage('Deploy') { 
            steps {
                echo "Deploying" 
		sh "spring-boot:build-image"
            }
        }
    }
}
