pipeline {
    agent any

	environment {
		mavenHome = tool 'jenkins-maven'
	}

	tools {
		jdk 'java-17'
	} 
    stages {
        stage('Build') { 
            steps {
                echo "Building" 
                bat "mvn clean install -DskipTests"
            }
        }
        stage('Test') { 
            steps {
                echo "Testing" 
                bat "mvn test"
            }
        }
        stage('Deploy') { 
            steps {
                echo "Deploying" 
            }
        }
    }
}
