pipeline {
    agent any 
    tools {
	maven 'maven'
	jdk 'jdk-17'
    }
    stages {
        stage('Build') { 
            steps {
		    dir('event-app'){
			echo "Building" 
			sh '''
   				env grep -e PATH -e JAVA_HOME
       				java -version
				mvn --version
				ls -la   
				mvn clean package
			'''
		    }
            }
        }
        stage('Test') { 
            steps {
                echo "Testing" 
                sh "./mvnw test"
            }
        }
        stage('Deploy') { 
            steps {
                echo "Deploying" 
		sh "mvnw spring-boot:build-image"
            }
        }
    }
}
