version: '2'
services:
  service-discovery:
    image: mak8docker/discovery-server:0.0.2-SNAPSHOT
    cap_add:
      - SYS_NICE
    restart: always
    depends_on:
      - attandance-db
    ports:
      - '8084:8084'

  api_gateway:
    image: mak8docker/api-gateway:0.0.2-SNAPSHOT
    cap_add:
      - SYS_NICE
    restart: always
    depends_on:
      - service-discovery
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-discovery:8084/eureka/
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin:9411/api/v2/spans
    ports:
      - '8089:8089'

  event-app:
    image: mak8docker/event-app:0.0.2-SNAPSHOT
    cap_add:
      - SYS_NICE
    restart: always
    depends_on:
      - kafka
    environment:
      SPRING.DATASOURCE.URL: jdbc:mysql://event-db:3306/event_db
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-discovery:8084/eureka/
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin:9411/api/v2/spans
    ports:
      - '8081:8081'

  attandance-app:
    image: mak8docker/attandance-app:0.0.2-SNAPSHOT
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-discovery:8084/eureka/
      SPRING.DATASOURCE.URL: jdbc:mysql://attandance-db:3306/attandance_db
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin:9411/api/v2/spans
    ports:
      - '8080:8080'
  
  config-server:
    image: mak8docker/config-server:0.0.2-SNAPSHOT
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin:9411/api/v2/spans
    ports:
      - '8088:8088'

  event-db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=event_db
      - MYSQL_USER=anas
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '23306:3306'
    volumes:
      - event_db:/var/lib/mysql

  attandance-db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    depends_on:
      - event-db
    environment:
      - MYSQL_DATABASE=attandance_db
      - MYSQL_USER=anas
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '23307:3306'
    volumes:
      - attandance_db:/var/lib/mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
  zipkin:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - '9411:9411'

  ## Prometheus
  prometheus:
    image: prom/prometheus:v2.37.1
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - attandance-app
      - event-app
      - config-server
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-oss:8.5.2
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    links:
      - prometheus:prometheus
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password




volumes:
  event_db:
    driver: local
  attandance_db:
    driver: local