version: '2'
services:
  service-discovery:
    image: mak8docker/discovery-server:0.0.1-SNAPSHOT
    cap_add:
      - SYS_NICE
    restart: always
    depends_on:
      - attandance_db
    networks:
      - ms-network
    ports:
      - '8084:8084'

  api_gateway:
    image: mak8docker/api-gateway:0.0.1-SNAPSHOT
    cap_add:
      - SYS_NICE
    restart: always
    depends_on:
      - service-discovery
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-discovery:8084/eureka/
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin:9411/api/v2/spans
    networks:
      - ms-network
    ports:
      - '8089:8089'

  event_app:
    image: mak8docker/event-app:0.0.1-SNAPSHOT
    cap_add:
      - SYS_NICE
    restart: always
    depends_on:
      - kafka
    networks:
      - ms-network
    environment:
      SPRING.DATASOURCE.URL: jdbc:mysql://event_db:3306/event_db
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-discovery:8084/eureka/
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin:9411/api/v2/spans
    ports:
      - '8081:8081'

  attandance_app:
    image: mak8docker/attandance-app:0.0.1-SNAPSHOT
    cap_add:
      - SYS_NICE
    restart: always
    networks:
      - ms-network
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-discovery:8084/eureka/
      SPRING.DATASOURCE.URL: jdbc:mysql://attandance_db:3306/attandance_db
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin:9411/api/v2/spans
    ports:
      - '8080:8080'

  event_db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=event_db
      - MYSQL_USER=anas
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - ms-network
    ports:
      - '23306:3306'
    volumes:
      - event_db:/var/lib/mysql

  attandance_db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    depends_on:
      - event_db
    networks:
      - ms-network
    environment:
      - MYSQL_DATABASE=attandance_db
      - MYSQL_USER=anas
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '23307:3306'
    volumes:
      - attandance_db:/var/lib/mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - ms-network
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    networks:
      - ms-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
  zipkin:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - '9411:9411'
    networks:
      - ms-network
networks:
  ms-network:

volumes:
  event_db:
    driver: local
  attandance_db:
    driver: local