global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'event-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['event-app:8081']
        labels:
          application: 'Event Service Application'
  - job_name: 'attandance-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['attandance-app:8080']
        labels:
          application: 'Attendance Service Application'
  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['config-server:8088']
        labels:
          application: 'Config-server Service Application'