apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: api-gateway
  name: api-gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - image: mak8docker/api-gateway:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: api-gateway
        env:
          - name: EUREKA.CLIENT.SERVICEURL.DEFAULTZONE
            value: http://service-discovery:8084/eureka/
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: default
spec:
  ports:
  - port: 8089
    protocol: TCP
    targetPort: 8089
  selector:
    app: api-gateway
  sessionAffinity: None
  type: NodePort
