apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak
  name: keycloak
  namespace: default
spec:
  ports:
    - name: "8060"
      port: 8060
      targetPort: 8080
  selector:
    io.kompose.service: keycloak
status:
  loadBalancer: {}
