apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: service-discovery
  name: service-discovery
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service-discovery
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/newfolder-default: "true"
        io.kompose.service: service-discovery
    spec:
      containers:
        - image: mak8docker/discovery-server:0.0.2-SNAPSHOT
          name: service-discovery
          ports:
            - containerPort: 8084
              hostPort: 8084
              protocol: TCP
          resources: {}
          securityContext:
            capabilities:
              add:
                - SYS_NICE
      restartPolicy: Always
status: {}
